sudo: required

services:
  - docker

script:
  - docker build -t proegssilb/rocketmap ./rocketmap/
  - docker build -t proegssilb/pokealarm ./pokealarm/

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push proegssilb/rocketmap;
    docker push proegssilb/pokealarm;
    fi
